kind = "web"
previewPath = "/"
title = "Lazy Brew's"
version = "1.0.0"
id = "artifacts/lazy-brews"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 22510
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/lazy-brews run dev"

[services.env]
PORT = "22510"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/lazy-brews", "run", "build"]
publicDir = "artifacts/lazy-brews/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
